// pages/product/[slug].js
import { useRouter } from "next/router";
import { getAllProductSlugs, getProductBySlug } from "../../lib/dataHelpers";
import Image from "next/image";
import NavBar from "@/components/NavBar";
import Head from "next/head";

const ProductPage = ({ product }) => {
  const router = useRouter();

  if (router.isFallback) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <>
        <Head>
          <title>{product.name}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/pest-logo.ico" />
        </Head>
      </>
      <NavBar />
      <div></div>

      <div className="flex flex-col justify-center items-center">
        <Image src={product.image} alt="Shoes" width={350} height={350} />
      </div>
      <h1 className="text-xl pl-8">{product.name}</h1>
      <h1 className="text-lg pl-8">£{product.price}</h1>
      <h1 className="text-lg pl-8">£{product.delivery}</h1>
      <ul className="menu menu-horizontal bg-base-300 rounded-box">
        <li>
          <a>Small</a>
        </li>
        <li>
          <a>Medium</a>
        </li>
        <li>
          <a>Large</a>
        </li>
      </ul>
    </>
  );
};

export async function getStaticPaths() {
  const slugs = getAllProductSlugs();

  const paths = slugs.map((slug) => ({
    params: { slug },
  }));

  return {
    paths,
    fallback: true, // If set to 'false', show a 404 error for non-existing slugs
  };
}

export async function getStaticProps({ params }) {
  const product = getProductBySlug(params.slug);

  if (!product) {
    return {
      notFound: true,
    };
  }

  return {
    props: { product },
  };
}

export default ProductPage;
