import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/NavBar'
import ApparelCard from '@/components/ApparelCard'


export default function Home() {
  return (
    <>
      <Head>
        <title>PEST Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pest-logo.ico" />
      </Head>
      <>
      <NavBar/>
      <div className='flex flex-col md:flex-row md:p-24 justify-center items-center'>
        <div className='pb-4 md:pr-4'>      
        <ApparelCard name="Jumper" description="Welcome to the rebellion." price="100" src="merch-1.png"/>
        </div>
        <div className='pb-4 md:pr-4'>      
        <ApparelCard name="T-shirt" description="Welcome to the rebellion." price="100" src="merch-2.png"/>
        </div>
        <div className='pb-4 md:pr-4'>      
        <ApparelCard name="Jumper 2" description="Welcome to the rebellion." price="100" src="merch-1.png"/>
        </div>
      </div>
     
      </>
    </>
  )
}
