import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/NavBar'
import ApparelCard from '@/components/ApparelCard'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pest-logo.ico" />
      </Head>
      <>
      <NavBar/>
      <div className='flex place-content-center
      '>
      <ApparelCard
  name="Dress"
  price="100"
  src="https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/en/images/products/200x200/134201_1.jpg"
/>
      </div>
     
      </>
    </>
  )
}
